server:
  port: ${SERVER_PORT:8082}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: jdbc:postgresql://${POSTGRES_SQL_HOST}:${POSTGRES_SQL_PORT}/${POSTGRES_SQL_DB}
    username: ${POSTGRES_SQL_USERNAME}
    password: ${POSTGRES_SQL_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

#logging:
#  level:
#    root: DEBUG
##    org.springframework.web: DEBUG
##    org.hibernate: ERROR
#  file:
#    name: ./logs/core-service.log
#  logback:
#    rollingpolicy:
#      max-file-size: 10MB
#      max-history: 30
#  pattern:
#    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %-5level - %msg%n"
#    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

queue:
  congratulation-birthday: ${RABBIT_CONGRATULATION_BIRTHDAY_QUEUE}
  registration-mail: ${RABBIT_REGISTRATION_MAIL_QUEUE}
  verification-mail: ${RABBIT_VERIFICATION_MAIL_QUEUE}
  answer-message-queue: ${RABBIT_ANSWER_MESSAGE_QUEUE}
  registration-state: ${RABBIT_REGISTRATION_STATE_QUEUE}
